/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsAndConditionsRouteImport } from './routes/terms-and-conditions'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as ContactUsRouteImport } from './routes/contact-us'
import { Route as CompanyProfileRouteImport } from './routes/company-profile'
import { Route as CompanyPoliciesRouteImport } from './routes/company-policies'
import { Route as TdsTcsRouteRouteImport } from './routes/tds-tcs.route'
import { Route as RegistrationsRouteRouteImport } from './routes/registrations.route'
import { Route as McaRouteRouteImport } from './routes/mca.route'
import { Route as IncomeTaxRouteRouteImport } from './routes/income-tax.route'
import { Route as GstRouteRouteImport } from './routes/gst.route'
import { Route as ConsultationRouteRouteImport } from './routes/consultation.route'
import { Route as ComplianceRouteRouteImport } from './routes/compliance.route'
import { Route as BlogRouteRouteImport } from './routes/blog.route'
import { Route as BankLoanRouteRouteImport } from './routes/bank-loan.route'
import { Route as AccountingAuditServicesRouteRouteImport } from './routes/accounting-audit-services.route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TdsTcsIndexRouteImport } from './routes/tds-tcs.index'
import { Route as RegistrationsIndexRouteImport } from './routes/registrations.index'
import { Route as McaIndexRouteImport } from './routes/mca.index'
import { Route as IncomeTaxIndexRouteImport } from './routes/income-tax.index'
import { Route as GstIndexRouteImport } from './routes/gst.index'
import { Route as ConsultationIndexRouteImport } from './routes/consultation.index'
import { Route as ComplianceIndexRouteImport } from './routes/compliance.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BankLoanIndexRouteImport } from './routes/bank-loan.index'
import { Route as AccountingAuditServicesIndexRouteImport } from './routes/accounting-audit-services.index'
import { Route as TdsTcsSlugRouteImport } from './routes/tds-tcs.$slug'
import { Route as RegistrationsSlugRouteImport } from './routes/registrations.$slug'
import { Route as McaSlugRouteImport } from './routes/mca.$slug'
import { Route as IncomeTaxSlugRouteImport } from './routes/income-tax.$slug'
import { Route as GstSlugRouteImport } from './routes/gst.$slug'
import { Route as ConsultationSlugRouteImport } from './routes/consultation.$slug'
import { Route as ComplianceSlugRouteImport } from './routes/compliance.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as BankLoanSlugRouteImport } from './routes/bank-loan.$slug'
import { Route as AccountingAuditServicesSlugRouteImport } from './routes/accounting-audit-services.$slug'

const TermsAndConditionsRoute = TermsAndConditionsRouteImport.update({
  id: '/terms-and-conditions',
  path: '/terms-and-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactUsRoute = ContactUsRouteImport.update({
  id: '/contact-us',
  path: '/contact-us',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyProfileRoute = CompanyProfileRouteImport.update({
  id: '/company-profile',
  path: '/company-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyPoliciesRoute = CompanyPoliciesRouteImport.update({
  id: '/company-policies',
  path: '/company-policies',
  getParentRoute: () => rootRouteImport,
} as any)
const TdsTcsRouteRoute = TdsTcsRouteRouteImport.update({
  id: '/tds-tcs',
  path: '/tds-tcs',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistrationsRouteRoute = RegistrationsRouteRouteImport.update({
  id: '/registrations',
  path: '/registrations',
  getParentRoute: () => rootRouteImport,
} as any)
const McaRouteRoute = McaRouteRouteImport.update({
  id: '/mca',
  path: '/mca',
  getParentRoute: () => rootRouteImport,
} as any)
const IncomeTaxRouteRoute = IncomeTaxRouteRouteImport.update({
  id: '/income-tax',
  path: '/income-tax',
  getParentRoute: () => rootRouteImport,
} as any)
const GstRouteRoute = GstRouteRouteImport.update({
  id: '/gst',
  path: '/gst',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultationRouteRoute = ConsultationRouteRouteImport.update({
  id: '/consultation',
  path: '/consultation',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceRouteRoute = ComplianceRouteRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRouteRoute = BlogRouteRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const BankLoanRouteRoute = BankLoanRouteRouteImport.update({
  id: '/bank-loan',
  path: '/bank-loan',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountingAuditServicesRouteRoute =
  AccountingAuditServicesRouteRouteImport.update({
    id: '/accounting-audit-services',
    path: '/accounting-audit-services',
    getParentRoute: () => rootRouteImport,
  } as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TdsTcsIndexRoute = TdsTcsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TdsTcsRouteRoute,
} as any)
const RegistrationsIndexRoute = RegistrationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RegistrationsRouteRoute,
} as any)
const McaIndexRoute = McaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => McaRouteRoute,
} as any)
const IncomeTaxIndexRoute = IncomeTaxIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => IncomeTaxRouteRoute,
} as any)
const GstIndexRoute = GstIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GstRouteRoute,
} as any)
const ConsultationIndexRoute = ConsultationIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ConsultationRouteRoute,
} as any)
const ComplianceIndexRoute = ComplianceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ComplianceRouteRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRouteRoute,
} as any)
const BankLoanIndexRoute = BankLoanIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BankLoanRouteRoute,
} as any)
const AccountingAuditServicesIndexRoute =
  AccountingAuditServicesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AccountingAuditServicesRouteRoute,
  } as any)
const TdsTcsSlugRoute = TdsTcsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => TdsTcsRouteRoute,
} as any)
const RegistrationsSlugRoute = RegistrationsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => RegistrationsRouteRoute,
} as any)
const McaSlugRoute = McaSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => McaRouteRoute,
} as any)
const IncomeTaxSlugRoute = IncomeTaxSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => IncomeTaxRouteRoute,
} as any)
const GstSlugRoute = GstSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => GstRouteRoute,
} as any)
const ConsultationSlugRoute = ConsultationSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ConsultationRouteRoute,
} as any)
const ComplianceSlugRoute = ComplianceSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ComplianceRouteRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRouteRoute,
} as any)
const BankLoanSlugRoute = BankLoanSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BankLoanRouteRoute,
} as any)
const AccountingAuditServicesSlugRoute =
  AccountingAuditServicesSlugRouteImport.update({
    id: '/$slug',
    path: '/$slug',
    getParentRoute: () => AccountingAuditServicesRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accounting-audit-services': typeof AccountingAuditServicesRouteRouteWithChildren
  '/bank-loan': typeof BankLoanRouteRouteWithChildren
  '/blog': typeof BlogRouteRouteWithChildren
  '/compliance': typeof ComplianceRouteRouteWithChildren
  '/consultation': typeof ConsultationRouteRouteWithChildren
  '/gst': typeof GstRouteRouteWithChildren
  '/income-tax': typeof IncomeTaxRouteRouteWithChildren
  '/mca': typeof McaRouteRouteWithChildren
  '/registrations': typeof RegistrationsRouteRouteWithChildren
  '/tds-tcs': typeof TdsTcsRouteRouteWithChildren
  '/company-policies': typeof CompanyPoliciesRoute
  '/company-profile': typeof CompanyProfileRoute
  '/contact-us': typeof ContactUsRoute
  '/disclaimer': typeof DisclaimerRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/accounting-audit-services/$slug': typeof AccountingAuditServicesSlugRoute
  '/bank-loan/$slug': typeof BankLoanSlugRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/compliance/$slug': typeof ComplianceSlugRoute
  '/consultation/$slug': typeof ConsultationSlugRoute
  '/gst/$slug': typeof GstSlugRoute
  '/income-tax/$slug': typeof IncomeTaxSlugRoute
  '/mca/$slug': typeof McaSlugRoute
  '/registrations/$slug': typeof RegistrationsSlugRoute
  '/tds-tcs/$slug': typeof TdsTcsSlugRoute
  '/accounting-audit-services/': typeof AccountingAuditServicesIndexRoute
  '/bank-loan/': typeof BankLoanIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/compliance/': typeof ComplianceIndexRoute
  '/consultation/': typeof ConsultationIndexRoute
  '/gst/': typeof GstIndexRoute
  '/income-tax/': typeof IncomeTaxIndexRoute
  '/mca/': typeof McaIndexRoute
  '/registrations/': typeof RegistrationsIndexRoute
  '/tds-tcs/': typeof TdsTcsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/company-policies': typeof CompanyPoliciesRoute
  '/company-profile': typeof CompanyProfileRoute
  '/contact-us': typeof ContactUsRoute
  '/disclaimer': typeof DisclaimerRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/accounting-audit-services/$slug': typeof AccountingAuditServicesSlugRoute
  '/bank-loan/$slug': typeof BankLoanSlugRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/compliance/$slug': typeof ComplianceSlugRoute
  '/consultation/$slug': typeof ConsultationSlugRoute
  '/gst/$slug': typeof GstSlugRoute
  '/income-tax/$slug': typeof IncomeTaxSlugRoute
  '/mca/$slug': typeof McaSlugRoute
  '/registrations/$slug': typeof RegistrationsSlugRoute
  '/tds-tcs/$slug': typeof TdsTcsSlugRoute
  '/accounting-audit-services': typeof AccountingAuditServicesIndexRoute
  '/bank-loan': typeof BankLoanIndexRoute
  '/blog': typeof BlogIndexRoute
  '/compliance': typeof ComplianceIndexRoute
  '/consultation': typeof ConsultationIndexRoute
  '/gst': typeof GstIndexRoute
  '/income-tax': typeof IncomeTaxIndexRoute
  '/mca': typeof McaIndexRoute
  '/registrations': typeof RegistrationsIndexRoute
  '/tds-tcs': typeof TdsTcsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accounting-audit-services': typeof AccountingAuditServicesRouteRouteWithChildren
  '/bank-loan': typeof BankLoanRouteRouteWithChildren
  '/blog': typeof BlogRouteRouteWithChildren
  '/compliance': typeof ComplianceRouteRouteWithChildren
  '/consultation': typeof ConsultationRouteRouteWithChildren
  '/gst': typeof GstRouteRouteWithChildren
  '/income-tax': typeof IncomeTaxRouteRouteWithChildren
  '/mca': typeof McaRouteRouteWithChildren
  '/registrations': typeof RegistrationsRouteRouteWithChildren
  '/tds-tcs': typeof TdsTcsRouteRouteWithChildren
  '/company-policies': typeof CompanyPoliciesRoute
  '/company-profile': typeof CompanyProfileRoute
  '/contact-us': typeof ContactUsRoute
  '/disclaimer': typeof DisclaimerRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/accounting-audit-services/$slug': typeof AccountingAuditServicesSlugRoute
  '/bank-loan/$slug': typeof BankLoanSlugRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/compliance/$slug': typeof ComplianceSlugRoute
  '/consultation/$slug': typeof ConsultationSlugRoute
  '/gst/$slug': typeof GstSlugRoute
  '/income-tax/$slug': typeof IncomeTaxSlugRoute
  '/mca/$slug': typeof McaSlugRoute
  '/registrations/$slug': typeof RegistrationsSlugRoute
  '/tds-tcs/$slug': typeof TdsTcsSlugRoute
  '/accounting-audit-services/': typeof AccountingAuditServicesIndexRoute
  '/bank-loan/': typeof BankLoanIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/compliance/': typeof ComplianceIndexRoute
  '/consultation/': typeof ConsultationIndexRoute
  '/gst/': typeof GstIndexRoute
  '/income-tax/': typeof IncomeTaxIndexRoute
  '/mca/': typeof McaIndexRoute
  '/registrations/': typeof RegistrationsIndexRoute
  '/tds-tcs/': typeof TdsTcsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounting-audit-services'
    | '/bank-loan'
    | '/blog'
    | '/compliance'
    | '/consultation'
    | '/gst'
    | '/income-tax'
    | '/mca'
    | '/registrations'
    | '/tds-tcs'
    | '/company-policies'
    | '/company-profile'
    | '/contact-us'
    | '/disclaimer'
    | '/privacy-policy'
    | '/terms-and-conditions'
    | '/accounting-audit-services/$slug'
    | '/bank-loan/$slug'
    | '/blog/$slug'
    | '/compliance/$slug'
    | '/consultation/$slug'
    | '/gst/$slug'
    | '/income-tax/$slug'
    | '/mca/$slug'
    | '/registrations/$slug'
    | '/tds-tcs/$slug'
    | '/accounting-audit-services/'
    | '/bank-loan/'
    | '/blog/'
    | '/compliance/'
    | '/consultation/'
    | '/gst/'
    | '/income-tax/'
    | '/mca/'
    | '/registrations/'
    | '/tds-tcs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/company-policies'
    | '/company-profile'
    | '/contact-us'
    | '/disclaimer'
    | '/privacy-policy'
    | '/terms-and-conditions'
    | '/accounting-audit-services/$slug'
    | '/bank-loan/$slug'
    | '/blog/$slug'
    | '/compliance/$slug'
    | '/consultation/$slug'
    | '/gst/$slug'
    | '/income-tax/$slug'
    | '/mca/$slug'
    | '/registrations/$slug'
    | '/tds-tcs/$slug'
    | '/accounting-audit-services'
    | '/bank-loan'
    | '/blog'
    | '/compliance'
    | '/consultation'
    | '/gst'
    | '/income-tax'
    | '/mca'
    | '/registrations'
    | '/tds-tcs'
  id:
    | '__root__'
    | '/'
    | '/accounting-audit-services'
    | '/bank-loan'
    | '/blog'
    | '/compliance'
    | '/consultation'
    | '/gst'
    | '/income-tax'
    | '/mca'
    | '/registrations'
    | '/tds-tcs'
    | '/company-policies'
    | '/company-profile'
    | '/contact-us'
    | '/disclaimer'
    | '/privacy-policy'
    | '/terms-and-conditions'
    | '/accounting-audit-services/$slug'
    | '/bank-loan/$slug'
    | '/blog/$slug'
    | '/compliance/$slug'
    | '/consultation/$slug'
    | '/gst/$slug'
    | '/income-tax/$slug'
    | '/mca/$slug'
    | '/registrations/$slug'
    | '/tds-tcs/$slug'
    | '/accounting-audit-services/'
    | '/bank-loan/'
    | '/blog/'
    | '/compliance/'
    | '/consultation/'
    | '/gst/'
    | '/income-tax/'
    | '/mca/'
    | '/registrations/'
    | '/tds-tcs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountingAuditServicesRouteRoute: typeof AccountingAuditServicesRouteRouteWithChildren
  BankLoanRouteRoute: typeof BankLoanRouteRouteWithChildren
  BlogRouteRoute: typeof BlogRouteRouteWithChildren
  ComplianceRouteRoute: typeof ComplianceRouteRouteWithChildren
  ConsultationRouteRoute: typeof ConsultationRouteRouteWithChildren
  GstRouteRoute: typeof GstRouteRouteWithChildren
  IncomeTaxRouteRoute: typeof IncomeTaxRouteRouteWithChildren
  McaRouteRoute: typeof McaRouteRouteWithChildren
  RegistrationsRouteRoute: typeof RegistrationsRouteRouteWithChildren
  TdsTcsRouteRoute: typeof TdsTcsRouteRouteWithChildren
  CompanyPoliciesRoute: typeof CompanyPoliciesRoute
  CompanyProfileRoute: typeof CompanyProfileRoute
  ContactUsRoute: typeof ContactUsRoute
  DisclaimerRoute: typeof DisclaimerRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  TermsAndConditionsRoute: typeof TermsAndConditionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms-and-conditions': {
      id: '/terms-and-conditions'
      path: '/terms-and-conditions'
      fullPath: '/terms-and-conditions'
      preLoaderRoute: typeof TermsAndConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact-us': {
      id: '/contact-us'
      path: '/contact-us'
      fullPath: '/contact-us'
      preLoaderRoute: typeof ContactUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company-profile': {
      id: '/company-profile'
      path: '/company-profile'
      fullPath: '/company-profile'
      preLoaderRoute: typeof CompanyProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company-policies': {
      id: '/company-policies'
      path: '/company-policies'
      fullPath: '/company-policies'
      preLoaderRoute: typeof CompanyPoliciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tds-tcs': {
      id: '/tds-tcs'
      path: '/tds-tcs'
      fullPath: '/tds-tcs'
      preLoaderRoute: typeof TdsTcsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registrations': {
      id: '/registrations'
      path: '/registrations'
      fullPath: '/registrations'
      preLoaderRoute: typeof RegistrationsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mca': {
      id: '/mca'
      path: '/mca'
      fullPath: '/mca'
      preLoaderRoute: typeof McaRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/income-tax': {
      id: '/income-tax'
      path: '/income-tax'
      fullPath: '/income-tax'
      preLoaderRoute: typeof IncomeTaxRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gst': {
      id: '/gst'
      path: '/gst'
      fullPath: '/gst'
      preLoaderRoute: typeof GstRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultation': {
      id: '/consultation'
      path: '/consultation'
      fullPath: '/consultation'
      preLoaderRoute: typeof ConsultationRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance': {
      id: '/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof ComplianceRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bank-loan': {
      id: '/bank-loan'
      path: '/bank-loan'
      fullPath: '/bank-loan'
      preLoaderRoute: typeof BankLoanRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounting-audit-services': {
      id: '/accounting-audit-services'
      path: '/accounting-audit-services'
      fullPath: '/accounting-audit-services'
      preLoaderRoute: typeof AccountingAuditServicesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tds-tcs/': {
      id: '/tds-tcs/'
      path: '/'
      fullPath: '/tds-tcs/'
      preLoaderRoute: typeof TdsTcsIndexRouteImport
      parentRoute: typeof TdsTcsRouteRoute
    }
    '/registrations/': {
      id: '/registrations/'
      path: '/'
      fullPath: '/registrations/'
      preLoaderRoute: typeof RegistrationsIndexRouteImport
      parentRoute: typeof RegistrationsRouteRoute
    }
    '/mca/': {
      id: '/mca/'
      path: '/'
      fullPath: '/mca/'
      preLoaderRoute: typeof McaIndexRouteImport
      parentRoute: typeof McaRouteRoute
    }
    '/income-tax/': {
      id: '/income-tax/'
      path: '/'
      fullPath: '/income-tax/'
      preLoaderRoute: typeof IncomeTaxIndexRouteImport
      parentRoute: typeof IncomeTaxRouteRoute
    }
    '/gst/': {
      id: '/gst/'
      path: '/'
      fullPath: '/gst/'
      preLoaderRoute: typeof GstIndexRouteImport
      parentRoute: typeof GstRouteRoute
    }
    '/consultation/': {
      id: '/consultation/'
      path: '/'
      fullPath: '/consultation/'
      preLoaderRoute: typeof ConsultationIndexRouteImport
      parentRoute: typeof ConsultationRouteRoute
    }
    '/compliance/': {
      id: '/compliance/'
      path: '/'
      fullPath: '/compliance/'
      preLoaderRoute: typeof ComplianceIndexRouteImport
      parentRoute: typeof ComplianceRouteRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRouteRoute
    }
    '/bank-loan/': {
      id: '/bank-loan/'
      path: '/'
      fullPath: '/bank-loan/'
      preLoaderRoute: typeof BankLoanIndexRouteImport
      parentRoute: typeof BankLoanRouteRoute
    }
    '/accounting-audit-services/': {
      id: '/accounting-audit-services/'
      path: '/'
      fullPath: '/accounting-audit-services/'
      preLoaderRoute: typeof AccountingAuditServicesIndexRouteImport
      parentRoute: typeof AccountingAuditServicesRouteRoute
    }
    '/tds-tcs/$slug': {
      id: '/tds-tcs/$slug'
      path: '/$slug'
      fullPath: '/tds-tcs/$slug'
      preLoaderRoute: typeof TdsTcsSlugRouteImport
      parentRoute: typeof TdsTcsRouteRoute
    }
    '/registrations/$slug': {
      id: '/registrations/$slug'
      path: '/$slug'
      fullPath: '/registrations/$slug'
      preLoaderRoute: typeof RegistrationsSlugRouteImport
      parentRoute: typeof RegistrationsRouteRoute
    }
    '/mca/$slug': {
      id: '/mca/$slug'
      path: '/$slug'
      fullPath: '/mca/$slug'
      preLoaderRoute: typeof McaSlugRouteImport
      parentRoute: typeof McaRouteRoute
    }
    '/income-tax/$slug': {
      id: '/income-tax/$slug'
      path: '/$slug'
      fullPath: '/income-tax/$slug'
      preLoaderRoute: typeof IncomeTaxSlugRouteImport
      parentRoute: typeof IncomeTaxRouteRoute
    }
    '/gst/$slug': {
      id: '/gst/$slug'
      path: '/$slug'
      fullPath: '/gst/$slug'
      preLoaderRoute: typeof GstSlugRouteImport
      parentRoute: typeof GstRouteRoute
    }
    '/consultation/$slug': {
      id: '/consultation/$slug'
      path: '/$slug'
      fullPath: '/consultation/$slug'
      preLoaderRoute: typeof ConsultationSlugRouteImport
      parentRoute: typeof ConsultationRouteRoute
    }
    '/compliance/$slug': {
      id: '/compliance/$slug'
      path: '/$slug'
      fullPath: '/compliance/$slug'
      preLoaderRoute: typeof ComplianceSlugRouteImport
      parentRoute: typeof ComplianceRouteRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRouteRoute
    }
    '/bank-loan/$slug': {
      id: '/bank-loan/$slug'
      path: '/$slug'
      fullPath: '/bank-loan/$slug'
      preLoaderRoute: typeof BankLoanSlugRouteImport
      parentRoute: typeof BankLoanRouteRoute
    }
    '/accounting-audit-services/$slug': {
      id: '/accounting-audit-services/$slug'
      path: '/$slug'
      fullPath: '/accounting-audit-services/$slug'
      preLoaderRoute: typeof AccountingAuditServicesSlugRouteImport
      parentRoute: typeof AccountingAuditServicesRouteRoute
    }
  }
}

interface AccountingAuditServicesRouteRouteChildren {
  AccountingAuditServicesSlugRoute: typeof AccountingAuditServicesSlugRoute
  AccountingAuditServicesIndexRoute: typeof AccountingAuditServicesIndexRoute
}

const AccountingAuditServicesRouteRouteChildren: AccountingAuditServicesRouteRouteChildren =
  {
    AccountingAuditServicesSlugRoute: AccountingAuditServicesSlugRoute,
    AccountingAuditServicesIndexRoute: AccountingAuditServicesIndexRoute,
  }

const AccountingAuditServicesRouteRouteWithChildren =
  AccountingAuditServicesRouteRoute._addFileChildren(
    AccountingAuditServicesRouteRouteChildren,
  )

interface BankLoanRouteRouteChildren {
  BankLoanSlugRoute: typeof BankLoanSlugRoute
  BankLoanIndexRoute: typeof BankLoanIndexRoute
}

const BankLoanRouteRouteChildren: BankLoanRouteRouteChildren = {
  BankLoanSlugRoute: BankLoanSlugRoute,
  BankLoanIndexRoute: BankLoanIndexRoute,
}

const BankLoanRouteRouteWithChildren = BankLoanRouteRoute._addFileChildren(
  BankLoanRouteRouteChildren,
)

interface BlogRouteRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteRouteChildren: BlogRouteRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteRouteWithChildren = BlogRouteRoute._addFileChildren(
  BlogRouteRouteChildren,
)

interface ComplianceRouteRouteChildren {
  ComplianceSlugRoute: typeof ComplianceSlugRoute
  ComplianceIndexRoute: typeof ComplianceIndexRoute
}

const ComplianceRouteRouteChildren: ComplianceRouteRouteChildren = {
  ComplianceSlugRoute: ComplianceSlugRoute,
  ComplianceIndexRoute: ComplianceIndexRoute,
}

const ComplianceRouteRouteWithChildren = ComplianceRouteRoute._addFileChildren(
  ComplianceRouteRouteChildren,
)

interface ConsultationRouteRouteChildren {
  ConsultationSlugRoute: typeof ConsultationSlugRoute
  ConsultationIndexRoute: typeof ConsultationIndexRoute
}

const ConsultationRouteRouteChildren: ConsultationRouteRouteChildren = {
  ConsultationSlugRoute: ConsultationSlugRoute,
  ConsultationIndexRoute: ConsultationIndexRoute,
}

const ConsultationRouteRouteWithChildren =
  ConsultationRouteRoute._addFileChildren(ConsultationRouteRouteChildren)

interface GstRouteRouteChildren {
  GstSlugRoute: typeof GstSlugRoute
  GstIndexRoute: typeof GstIndexRoute
}

const GstRouteRouteChildren: GstRouteRouteChildren = {
  GstSlugRoute: GstSlugRoute,
  GstIndexRoute: GstIndexRoute,
}

const GstRouteRouteWithChildren = GstRouteRoute._addFileChildren(
  GstRouteRouteChildren,
)

interface IncomeTaxRouteRouteChildren {
  IncomeTaxSlugRoute: typeof IncomeTaxSlugRoute
  IncomeTaxIndexRoute: typeof IncomeTaxIndexRoute
}

const IncomeTaxRouteRouteChildren: IncomeTaxRouteRouteChildren = {
  IncomeTaxSlugRoute: IncomeTaxSlugRoute,
  IncomeTaxIndexRoute: IncomeTaxIndexRoute,
}

const IncomeTaxRouteRouteWithChildren = IncomeTaxRouteRoute._addFileChildren(
  IncomeTaxRouteRouteChildren,
)

interface McaRouteRouteChildren {
  McaSlugRoute: typeof McaSlugRoute
  McaIndexRoute: typeof McaIndexRoute
}

const McaRouteRouteChildren: McaRouteRouteChildren = {
  McaSlugRoute: McaSlugRoute,
  McaIndexRoute: McaIndexRoute,
}

const McaRouteRouteWithChildren = McaRouteRoute._addFileChildren(
  McaRouteRouteChildren,
)

interface RegistrationsRouteRouteChildren {
  RegistrationsSlugRoute: typeof RegistrationsSlugRoute
  RegistrationsIndexRoute: typeof RegistrationsIndexRoute
}

const RegistrationsRouteRouteChildren: RegistrationsRouteRouteChildren = {
  RegistrationsSlugRoute: RegistrationsSlugRoute,
  RegistrationsIndexRoute: RegistrationsIndexRoute,
}

const RegistrationsRouteRouteWithChildren =
  RegistrationsRouteRoute._addFileChildren(RegistrationsRouteRouteChildren)

interface TdsTcsRouteRouteChildren {
  TdsTcsSlugRoute: typeof TdsTcsSlugRoute
  TdsTcsIndexRoute: typeof TdsTcsIndexRoute
}

const TdsTcsRouteRouteChildren: TdsTcsRouteRouteChildren = {
  TdsTcsSlugRoute: TdsTcsSlugRoute,
  TdsTcsIndexRoute: TdsTcsIndexRoute,
}

const TdsTcsRouteRouteWithChildren = TdsTcsRouteRoute._addFileChildren(
  TdsTcsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountingAuditServicesRouteRoute:
    AccountingAuditServicesRouteRouteWithChildren,
  BankLoanRouteRoute: BankLoanRouteRouteWithChildren,
  BlogRouteRoute: BlogRouteRouteWithChildren,
  ComplianceRouteRoute: ComplianceRouteRouteWithChildren,
  ConsultationRouteRoute: ConsultationRouteRouteWithChildren,
  GstRouteRoute: GstRouteRouteWithChildren,
  IncomeTaxRouteRoute: IncomeTaxRouteRouteWithChildren,
  McaRouteRoute: McaRouteRouteWithChildren,
  RegistrationsRouteRoute: RegistrationsRouteRouteWithChildren,
  TdsTcsRouteRoute: TdsTcsRouteRouteWithChildren,
  CompanyPoliciesRoute: CompanyPoliciesRoute,
  CompanyProfileRoute: CompanyProfileRoute,
  ContactUsRoute: ContactUsRoute,
  DisclaimerRoute: DisclaimerRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  TermsAndConditionsRoute: TermsAndConditionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
