/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsAndConditionsRouteImport } from './routes/terms-and-conditions'
import { Route as TaxRegistrationServicesRouteImport } from './routes/tax-registration-services'
import { Route as TaxHolidaySection80iacServicesRouteImport } from './routes/tax-holiday-section-80iac-services'
import { Route as StartupNgoRegistrationServicesRouteImport } from './routes/startup-ngo-registration-services'
import { Route as StartupIndiaDpiitRegistrationServicesRouteImport } from './routes/startup-india-dpiit-registration-services'
import { Route as StartupGrantLoanAssistanceServicesRouteImport } from './routes/startup-grant-loan-assistance-services'
import { Route as SoleProprietorshipRegistrationServicesRouteImport } from './routes/sole-proprietorship-registration-services'
import { Route as ShopAndEstablishmentRegistrationServicesRouteImport } from './routes/shop-and-establishment-registration-services'
import { Route as ProfessionalTaxRegistrationServicesRouteImport } from './routes/professional-tax-registration-services'
import { Route as PrivateLimitedCompanyRouteImport } from './routes/private-limited-company'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as PartnershipFirmRegistrationServicesRouteImport } from './routes/partnership-firm-registration-services'
import { Route as PartnershipFirmRouteImport } from './routes/partnership-firm'
import { Route as OurFullPackagesServicesRouteImport } from './routes/our-full-packages-services'
import { Route as MsmeUdyamRegistrationServicesRouteImport } from './routes/msme-udyam-registration-services'
import { Route as LlpCompliancePackagesRouteImport } from './routes/llp-compliance-packages'
import { Route as ImportExportCodeIecRegistrationServicesRouteImport } from './routes/import-export-code-iec-registration-services'
import { Route as HufFormationRegistrationServicesRouteImport } from './routes/huf-formation-registration-services'
import { Route as GstRegistrationReturnFilingServicesRouteImport } from './routes/gst-registration-return-filing-services'
import { Route as FssaiFoodLicenseRegistrationServicesRouteImport } from './routes/fssai-food-license-registration-services'
import { Route as EsicPfRegistrationServicesRouteImport } from './routes/esic-pf-registration-services'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as DigitalSignatureDscRegistrationServicesRouteImport } from './routes/digital-signature-dsc-registration-services'
import { Route as DigitalBusinessServicesRouteImport } from './routes/digital-business-services'
import { Route as ContactUsRouteImport } from './routes/contact-us'
import { Route as CompanyProfileRouteImport } from './routes/company-profile'
import { Route as CompanyPoliciesRouteImport } from './routes/company-policies'
import { Route as BusinessSetupServicesRouteImport } from './routes/business-setup-services'
import { Route as BusinessRegistrationLicensesRouteImport } from './routes/business-registration-licenses'
import { Route as R80g12aaRegistrationServicesRouteImport } from './routes/80g-12aa-registration-services'
import { Route as TdsTcsRouteRouteImport } from './routes/tds-tcs.route'
import { Route as RegistrationsRouteRouteImport } from './routes/registrations.route'
import { Route as McaRouteRouteImport } from './routes/mca.route'
import { Route as IncomeTaxRouteRouteImport } from './routes/income-tax.route'
import { Route as GstRouteRouteImport } from './routes/gst.route'
import { Route as ConsultationRouteRouteImport } from './routes/consultation.route'
import { Route as ComplianceRouteRouteImport } from './routes/compliance.route'
import { Route as BlogRouteRouteImport } from './routes/blog.route'
import { Route as BankLoanRouteRouteImport } from './routes/bank-loan.route'
import { Route as AccountingAuditServicesRouteRouteImport } from './routes/accounting-audit-services.route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TdsTcsIndexRouteImport } from './routes/tds-tcs.index'
import { Route as RegistrationsIndexRouteImport } from './routes/registrations.index'
import { Route as McaIndexRouteImport } from './routes/mca.index'
import { Route as IncomeTaxIndexRouteImport } from './routes/income-tax.index'
import { Route as ConsultationIndexRouteImport } from './routes/consultation.index'
import { Route as ComplianceIndexRouteImport } from './routes/compliance.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BankLoanIndexRouteImport } from './routes/bank-loan.index'
import { Route as AccountingAuditServicesIndexRouteImport } from './routes/accounting-audit-services.index'
import { Route as TdsTcsSlugRouteImport } from './routes/tds-tcs.$slug'
import { Route as RegistrationsSlugRouteImport } from './routes/registrations.$slug'
import { Route as McaSlugRouteImport } from './routes/mca.$slug'
import { Route as IncomeTaxSlugRouteImport } from './routes/income-tax.$slug'
import { Route as GstSlugRouteImport } from './routes/gst.$slug'
import { Route as ConsultationSlugRouteImport } from './routes/consultation.$slug'
import { Route as ComplianceSlugRouteImport } from './routes/compliance.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as BankLoanSlugRouteImport } from './routes/bank-loan.$slug'
import { Route as AccountingAuditServicesSlugRouteImport } from './routes/accounting-audit-services.$slug'

const TermsAndConditionsRoute = TermsAndConditionsRouteImport.update({
  id: '/terms-and-conditions',
  path: '/terms-and-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const TaxRegistrationServicesRoute = TaxRegistrationServicesRouteImport.update({
  id: '/tax-registration-services',
  path: '/tax-registration-services',
  getParentRoute: () => rootRouteImport,
} as any)
const TaxHolidaySection80iacServicesRoute =
  TaxHolidaySection80iacServicesRouteImport.update({
    id: '/tax-holiday-section-80iac-services',
    path: '/tax-holiday-section-80iac-services',
    getParentRoute: () => rootRouteImport,
  } as any)
const StartupNgoRegistrationServicesRoute =
  StartupNgoRegistrationServicesRouteImport.update({
    id: '/startup-ngo-registration-services',
    path: '/startup-ngo-registration-services',
    getParentRoute: () => rootRouteImport,
  } as any)
const StartupIndiaDpiitRegistrationServicesRoute =
  StartupIndiaDpiitRegistrationServicesRouteImport.update({
    id: '/startup-india-dpiit-registration-services',
    path: '/startup-india-dpiit-registration-services',
    getParentRoute: () => rootRouteImport,
  } as any)
const StartupGrantLoanAssistanceServicesRoute =
  StartupGrantLoanAssistanceServicesRouteImport.update({
    id: '/startup-grant-loan-assistance-services',
    path: '/startup-grant-loan-assistance-services',
    getParentRoute: () => rootRouteImport,
  } as any)
const SoleProprietorshipRegistrationServicesRoute =
  SoleProprietorshipRegistrationServicesRouteImport.update({
    id: '/sole-proprietorship-registration-services',
    path: '/sole-proprietorship-registration-services',
    getParentRoute: () => rootRouteImport,
  } as any)
const ShopAndEstablishmentRegistrationServicesRoute =
  ShopAndEstablishmentRegistrationServicesRouteImport.update({
    id: '/shop-and-establishment-registration-services',
    path: '/shop-and-establishment-registration-services',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProfessionalTaxRegistrationServicesRoute =
  ProfessionalTaxRegistrationServicesRouteImport.update({
    id: '/professional-tax-registration-services',
    path: '/professional-tax-registration-services',
    getParentRoute: () => rootRouteImport,
  } as any)
const PrivateLimitedCompanyRoute = PrivateLimitedCompanyRouteImport.update({
  id: '/private-limited-company',
  path: '/private-limited-company',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnershipFirmRegistrationServicesRoute =
  PartnershipFirmRegistrationServicesRouteImport.update({
    id: '/partnership-firm-registration-services',
    path: '/partnership-firm-registration-services',
    getParentRoute: () => rootRouteImport,
  } as any)
const PartnershipFirmRoute = PartnershipFirmRouteImport.update({
  id: '/partnership-firm',
  path: '/partnership-firm',
  getParentRoute: () => rootRouteImport,
} as any)
const OurFullPackagesServicesRoute = OurFullPackagesServicesRouteImport.update({
  id: '/our-full-packages-services',
  path: '/our-full-packages-services',
  getParentRoute: () => rootRouteImport,
} as any)
const MsmeUdyamRegistrationServicesRoute =
  MsmeUdyamRegistrationServicesRouteImport.update({
    id: '/msme-udyam-registration-services',
    path: '/msme-udyam-registration-services',
    getParentRoute: () => rootRouteImport,
  } as any)
const LlpCompliancePackagesRoute = LlpCompliancePackagesRouteImport.update({
  id: '/llp-compliance-packages',
  path: '/llp-compliance-packages',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportExportCodeIecRegistrationServicesRoute =
  ImportExportCodeIecRegistrationServicesRouteImport.update({
    id: '/import-export-code-iec-registration-services',
    path: '/import-export-code-iec-registration-services',
    getParentRoute: () => rootRouteImport,
  } as any)
const HufFormationRegistrationServicesRoute =
  HufFormationRegistrationServicesRouteImport.update({
    id: '/huf-formation-registration-services',
    path: '/huf-formation-registration-services',
    getParentRoute: () => rootRouteImport,
  } as any)
const GstRegistrationReturnFilingServicesRoute =
  GstRegistrationReturnFilingServicesRouteImport.update({
    id: '/gst-registration-return-filing-services',
    path: '/gst-registration-return-filing-services',
    getParentRoute: () => rootRouteImport,
  } as any)
const FssaiFoodLicenseRegistrationServicesRoute =
  FssaiFoodLicenseRegistrationServicesRouteImport.update({
    id: '/fssai-food-license-registration-services',
    path: '/fssai-food-license-registration-services',
    getParentRoute: () => rootRouteImport,
  } as any)
const EsicPfRegistrationServicesRoute =
  EsicPfRegistrationServicesRouteImport.update({
    id: '/esic-pf-registration-services',
    path: '/esic-pf-registration-services',
    getParentRoute: () => rootRouteImport,
  } as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const DigitalSignatureDscRegistrationServicesRoute =
  DigitalSignatureDscRegistrationServicesRouteImport.update({
    id: '/digital-signature-dsc-registration-services',
    path: '/digital-signature-dsc-registration-services',
    getParentRoute: () => rootRouteImport,
  } as any)
const DigitalBusinessServicesRoute = DigitalBusinessServicesRouteImport.update({
  id: '/digital-business-services',
  path: '/digital-business-services',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactUsRoute = ContactUsRouteImport.update({
  id: '/contact-us',
  path: '/contact-us',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyProfileRoute = CompanyProfileRouteImport.update({
  id: '/company-profile',
  path: '/company-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyPoliciesRoute = CompanyPoliciesRouteImport.update({
  id: '/company-policies',
  path: '/company-policies',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessSetupServicesRoute = BusinessSetupServicesRouteImport.update({
  id: '/business-setup-services',
  path: '/business-setup-services',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessRegistrationLicensesRoute =
  BusinessRegistrationLicensesRouteImport.update({
    id: '/business-registration-licenses',
    path: '/business-registration-licenses',
    getParentRoute: () => rootRouteImport,
  } as any)
const R80g12aaRegistrationServicesRoute =
  R80g12aaRegistrationServicesRouteImport.update({
    id: '/80g-12aa-registration-services',
    path: '/80g-12aa-registration-services',
    getParentRoute: () => rootRouteImport,
  } as any)
const TdsTcsRouteRoute = TdsTcsRouteRouteImport.update({
  id: '/tds-tcs',
  path: '/tds-tcs',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistrationsRouteRoute = RegistrationsRouteRouteImport.update({
  id: '/registrations',
  path: '/registrations',
  getParentRoute: () => rootRouteImport,
} as any)
const McaRouteRoute = McaRouteRouteImport.update({
  id: '/mca',
  path: '/mca',
  getParentRoute: () => rootRouteImport,
} as any)
const IncomeTaxRouteRoute = IncomeTaxRouteRouteImport.update({
  id: '/income-tax',
  path: '/income-tax',
  getParentRoute: () => rootRouteImport,
} as any)
const GstRouteRoute = GstRouteRouteImport.update({
  id: '/gst',
  path: '/gst',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultationRouteRoute = ConsultationRouteRouteImport.update({
  id: '/consultation',
  path: '/consultation',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceRouteRoute = ComplianceRouteRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRouteRoute = BlogRouteRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const BankLoanRouteRoute = BankLoanRouteRouteImport.update({
  id: '/bank-loan',
  path: '/bank-loan',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountingAuditServicesRouteRoute =
  AccountingAuditServicesRouteRouteImport.update({
    id: '/accounting-audit-services',
    path: '/accounting-audit-services',
    getParentRoute: () => rootRouteImport,
  } as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TdsTcsIndexRoute = TdsTcsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TdsTcsRouteRoute,
} as any)
const RegistrationsIndexRoute = RegistrationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RegistrationsRouteRoute,
} as any)
const McaIndexRoute = McaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => McaRouteRoute,
} as any)
const IncomeTaxIndexRoute = IncomeTaxIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => IncomeTaxRouteRoute,
} as any)
const ConsultationIndexRoute = ConsultationIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ConsultationRouteRoute,
} as any)
const ComplianceIndexRoute = ComplianceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ComplianceRouteRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRouteRoute,
} as any)
const BankLoanIndexRoute = BankLoanIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BankLoanRouteRoute,
} as any)
const AccountingAuditServicesIndexRoute =
  AccountingAuditServicesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AccountingAuditServicesRouteRoute,
  } as any)
const TdsTcsSlugRoute = TdsTcsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => TdsTcsRouteRoute,
} as any)
const RegistrationsSlugRoute = RegistrationsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => RegistrationsRouteRoute,
} as any)
const McaSlugRoute = McaSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => McaRouteRoute,
} as any)
const IncomeTaxSlugRoute = IncomeTaxSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => IncomeTaxRouteRoute,
} as any)
const GstSlugRoute = GstSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => GstRouteRoute,
} as any)
const ConsultationSlugRoute = ConsultationSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ConsultationRouteRoute,
} as any)
const ComplianceSlugRoute = ComplianceSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ComplianceRouteRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRouteRoute,
} as any)
const BankLoanSlugRoute = BankLoanSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BankLoanRouteRoute,
} as any)
const AccountingAuditServicesSlugRoute =
  AccountingAuditServicesSlugRouteImport.update({
    id: '/$slug',
    path: '/$slug',
    getParentRoute: () => AccountingAuditServicesRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accounting-audit-services': typeof AccountingAuditServicesRouteRouteWithChildren
  '/bank-loan': typeof BankLoanRouteRouteWithChildren
  '/blog': typeof BlogRouteRouteWithChildren
  '/compliance': typeof ComplianceRouteRouteWithChildren
  '/consultation': typeof ConsultationRouteRouteWithChildren
  '/gst': typeof GstRouteRouteWithChildren
  '/income-tax': typeof IncomeTaxRouteRouteWithChildren
  '/mca': typeof McaRouteRouteWithChildren
  '/registrations': typeof RegistrationsRouteRouteWithChildren
  '/tds-tcs': typeof TdsTcsRouteRouteWithChildren
  '/80g-12aa-registration-services': typeof R80g12aaRegistrationServicesRoute
  '/business-registration-licenses': typeof BusinessRegistrationLicensesRoute
  '/business-setup-services': typeof BusinessSetupServicesRoute
  '/company-policies': typeof CompanyPoliciesRoute
  '/company-profile': typeof CompanyProfileRoute
  '/contact-us': typeof ContactUsRoute
  '/digital-business-services': typeof DigitalBusinessServicesRoute
  '/digital-signature-dsc-registration-services': typeof DigitalSignatureDscRegistrationServicesRoute
  '/disclaimer': typeof DisclaimerRoute
  '/esic-pf-registration-services': typeof EsicPfRegistrationServicesRoute
  '/fssai-food-license-registration-services': typeof FssaiFoodLicenseRegistrationServicesRoute
  '/gst-registration-return-filing-services': typeof GstRegistrationReturnFilingServicesRoute
  '/huf-formation-registration-services': typeof HufFormationRegistrationServicesRoute
  '/import-export-code-iec-registration-services': typeof ImportExportCodeIecRegistrationServicesRoute
  '/llp-compliance-packages': typeof LlpCompliancePackagesRoute
  '/msme-udyam-registration-services': typeof MsmeUdyamRegistrationServicesRoute
  '/our-full-packages-services': typeof OurFullPackagesServicesRoute
  '/partnership-firm': typeof PartnershipFirmRoute
  '/partnership-firm-registration-services': typeof PartnershipFirmRegistrationServicesRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/private-limited-company': typeof PrivateLimitedCompanyRoute
  '/professional-tax-registration-services': typeof ProfessionalTaxRegistrationServicesRoute
  '/shop-and-establishment-registration-services': typeof ShopAndEstablishmentRegistrationServicesRoute
  '/sole-proprietorship-registration-services': typeof SoleProprietorshipRegistrationServicesRoute
  '/startup-grant-loan-assistance-services': typeof StartupGrantLoanAssistanceServicesRoute
  '/startup-india-dpiit-registration-services': typeof StartupIndiaDpiitRegistrationServicesRoute
  '/startup-ngo-registration-services': typeof StartupNgoRegistrationServicesRoute
  '/tax-holiday-section-80iac-services': typeof TaxHolidaySection80iacServicesRoute
  '/tax-registration-services': typeof TaxRegistrationServicesRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/accounting-audit-services/$slug': typeof AccountingAuditServicesSlugRoute
  '/bank-loan/$slug': typeof BankLoanSlugRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/compliance/$slug': typeof ComplianceSlugRoute
  '/consultation/$slug': typeof ConsultationSlugRoute
  '/gst/$slug': typeof GstSlugRoute
  '/income-tax/$slug': typeof IncomeTaxSlugRoute
  '/mca/$slug': typeof McaSlugRoute
  '/registrations/$slug': typeof RegistrationsSlugRoute
  '/tds-tcs/$slug': typeof TdsTcsSlugRoute
  '/accounting-audit-services/': typeof AccountingAuditServicesIndexRoute
  '/bank-loan/': typeof BankLoanIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/compliance/': typeof ComplianceIndexRoute
  '/consultation/': typeof ConsultationIndexRoute
  '/income-tax/': typeof IncomeTaxIndexRoute
  '/mca/': typeof McaIndexRoute
  '/registrations/': typeof RegistrationsIndexRoute
  '/tds-tcs/': typeof TdsTcsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/gst': typeof GstRouteRouteWithChildren
  '/80g-12aa-registration-services': typeof R80g12aaRegistrationServicesRoute
  '/business-registration-licenses': typeof BusinessRegistrationLicensesRoute
  '/business-setup-services': typeof BusinessSetupServicesRoute
  '/company-policies': typeof CompanyPoliciesRoute
  '/company-profile': typeof CompanyProfileRoute
  '/contact-us': typeof ContactUsRoute
  '/digital-business-services': typeof DigitalBusinessServicesRoute
  '/digital-signature-dsc-registration-services': typeof DigitalSignatureDscRegistrationServicesRoute
  '/disclaimer': typeof DisclaimerRoute
  '/esic-pf-registration-services': typeof EsicPfRegistrationServicesRoute
  '/fssai-food-license-registration-services': typeof FssaiFoodLicenseRegistrationServicesRoute
  '/gst-registration-return-filing-services': typeof GstRegistrationReturnFilingServicesRoute
  '/huf-formation-registration-services': typeof HufFormationRegistrationServicesRoute
  '/import-export-code-iec-registration-services': typeof ImportExportCodeIecRegistrationServicesRoute
  '/llp-compliance-packages': typeof LlpCompliancePackagesRoute
  '/msme-udyam-registration-services': typeof MsmeUdyamRegistrationServicesRoute
  '/our-full-packages-services': typeof OurFullPackagesServicesRoute
  '/partnership-firm': typeof PartnershipFirmRoute
  '/partnership-firm-registration-services': typeof PartnershipFirmRegistrationServicesRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/private-limited-company': typeof PrivateLimitedCompanyRoute
  '/professional-tax-registration-services': typeof ProfessionalTaxRegistrationServicesRoute
  '/shop-and-establishment-registration-services': typeof ShopAndEstablishmentRegistrationServicesRoute
  '/sole-proprietorship-registration-services': typeof SoleProprietorshipRegistrationServicesRoute
  '/startup-grant-loan-assistance-services': typeof StartupGrantLoanAssistanceServicesRoute
  '/startup-india-dpiit-registration-services': typeof StartupIndiaDpiitRegistrationServicesRoute
  '/startup-ngo-registration-services': typeof StartupNgoRegistrationServicesRoute
  '/tax-holiday-section-80iac-services': typeof TaxHolidaySection80iacServicesRoute
  '/tax-registration-services': typeof TaxRegistrationServicesRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/accounting-audit-services/$slug': typeof AccountingAuditServicesSlugRoute
  '/bank-loan/$slug': typeof BankLoanSlugRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/compliance/$slug': typeof ComplianceSlugRoute
  '/consultation/$slug': typeof ConsultationSlugRoute
  '/gst/$slug': typeof GstSlugRoute
  '/income-tax/$slug': typeof IncomeTaxSlugRoute
  '/mca/$slug': typeof McaSlugRoute
  '/registrations/$slug': typeof RegistrationsSlugRoute
  '/tds-tcs/$slug': typeof TdsTcsSlugRoute
  '/accounting-audit-services': typeof AccountingAuditServicesIndexRoute
  '/bank-loan': typeof BankLoanIndexRoute
  '/blog': typeof BlogIndexRoute
  '/compliance': typeof ComplianceIndexRoute
  '/consultation': typeof ConsultationIndexRoute
  '/income-tax': typeof IncomeTaxIndexRoute
  '/mca': typeof McaIndexRoute
  '/registrations': typeof RegistrationsIndexRoute
  '/tds-tcs': typeof TdsTcsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accounting-audit-services': typeof AccountingAuditServicesRouteRouteWithChildren
  '/bank-loan': typeof BankLoanRouteRouteWithChildren
  '/blog': typeof BlogRouteRouteWithChildren
  '/compliance': typeof ComplianceRouteRouteWithChildren
  '/consultation': typeof ConsultationRouteRouteWithChildren
  '/gst': typeof GstRouteRouteWithChildren
  '/income-tax': typeof IncomeTaxRouteRouteWithChildren
  '/mca': typeof McaRouteRouteWithChildren
  '/registrations': typeof RegistrationsRouteRouteWithChildren
  '/tds-tcs': typeof TdsTcsRouteRouteWithChildren
  '/80g-12aa-registration-services': typeof R80g12aaRegistrationServicesRoute
  '/business-registration-licenses': typeof BusinessRegistrationLicensesRoute
  '/business-setup-services': typeof BusinessSetupServicesRoute
  '/company-policies': typeof CompanyPoliciesRoute
  '/company-profile': typeof CompanyProfileRoute
  '/contact-us': typeof ContactUsRoute
  '/digital-business-services': typeof DigitalBusinessServicesRoute
  '/digital-signature-dsc-registration-services': typeof DigitalSignatureDscRegistrationServicesRoute
  '/disclaimer': typeof DisclaimerRoute
  '/esic-pf-registration-services': typeof EsicPfRegistrationServicesRoute
  '/fssai-food-license-registration-services': typeof FssaiFoodLicenseRegistrationServicesRoute
  '/gst-registration-return-filing-services': typeof GstRegistrationReturnFilingServicesRoute
  '/huf-formation-registration-services': typeof HufFormationRegistrationServicesRoute
  '/import-export-code-iec-registration-services': typeof ImportExportCodeIecRegistrationServicesRoute
  '/llp-compliance-packages': typeof LlpCompliancePackagesRoute
  '/msme-udyam-registration-services': typeof MsmeUdyamRegistrationServicesRoute
  '/our-full-packages-services': typeof OurFullPackagesServicesRoute
  '/partnership-firm': typeof PartnershipFirmRoute
  '/partnership-firm-registration-services': typeof PartnershipFirmRegistrationServicesRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/private-limited-company': typeof PrivateLimitedCompanyRoute
  '/professional-tax-registration-services': typeof ProfessionalTaxRegistrationServicesRoute
  '/shop-and-establishment-registration-services': typeof ShopAndEstablishmentRegistrationServicesRoute
  '/sole-proprietorship-registration-services': typeof SoleProprietorshipRegistrationServicesRoute
  '/startup-grant-loan-assistance-services': typeof StartupGrantLoanAssistanceServicesRoute
  '/startup-india-dpiit-registration-services': typeof StartupIndiaDpiitRegistrationServicesRoute
  '/startup-ngo-registration-services': typeof StartupNgoRegistrationServicesRoute
  '/tax-holiday-section-80iac-services': typeof TaxHolidaySection80iacServicesRoute
  '/tax-registration-services': typeof TaxRegistrationServicesRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/accounting-audit-services/$slug': typeof AccountingAuditServicesSlugRoute
  '/bank-loan/$slug': typeof BankLoanSlugRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/compliance/$slug': typeof ComplianceSlugRoute
  '/consultation/$slug': typeof ConsultationSlugRoute
  '/gst/$slug': typeof GstSlugRoute
  '/income-tax/$slug': typeof IncomeTaxSlugRoute
  '/mca/$slug': typeof McaSlugRoute
  '/registrations/$slug': typeof RegistrationsSlugRoute
  '/tds-tcs/$slug': typeof TdsTcsSlugRoute
  '/accounting-audit-services/': typeof AccountingAuditServicesIndexRoute
  '/bank-loan/': typeof BankLoanIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/compliance/': typeof ComplianceIndexRoute
  '/consultation/': typeof ConsultationIndexRoute
  '/income-tax/': typeof IncomeTaxIndexRoute
  '/mca/': typeof McaIndexRoute
  '/registrations/': typeof RegistrationsIndexRoute
  '/tds-tcs/': typeof TdsTcsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounting-audit-services'
    | '/bank-loan'
    | '/blog'
    | '/compliance'
    | '/consultation'
    | '/gst'
    | '/income-tax'
    | '/mca'
    | '/registrations'
    | '/tds-tcs'
    | '/80g-12aa-registration-services'
    | '/business-registration-licenses'
    | '/business-setup-services'
    | '/company-policies'
    | '/company-profile'
    | '/contact-us'
    | '/digital-business-services'
    | '/digital-signature-dsc-registration-services'
    | '/disclaimer'
    | '/esic-pf-registration-services'
    | '/fssai-food-license-registration-services'
    | '/gst-registration-return-filing-services'
    | '/huf-formation-registration-services'
    | '/import-export-code-iec-registration-services'
    | '/llp-compliance-packages'
    | '/msme-udyam-registration-services'
    | '/our-full-packages-services'
    | '/partnership-firm'
    | '/partnership-firm-registration-services'
    | '/privacy-policy'
    | '/private-limited-company'
    | '/professional-tax-registration-services'
    | '/shop-and-establishment-registration-services'
    | '/sole-proprietorship-registration-services'
    | '/startup-grant-loan-assistance-services'
    | '/startup-india-dpiit-registration-services'
    | '/startup-ngo-registration-services'
    | '/tax-holiday-section-80iac-services'
    | '/tax-registration-services'
    | '/terms-and-conditions'
    | '/accounting-audit-services/$slug'
    | '/bank-loan/$slug'
    | '/blog/$slug'
    | '/compliance/$slug'
    | '/consultation/$slug'
    | '/gst/$slug'
    | '/income-tax/$slug'
    | '/mca/$slug'
    | '/registrations/$slug'
    | '/tds-tcs/$slug'
    | '/accounting-audit-services/'
    | '/bank-loan/'
    | '/blog/'
    | '/compliance/'
    | '/consultation/'
    | '/income-tax/'
    | '/mca/'
    | '/registrations/'
    | '/tds-tcs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/gst'
    | '/80g-12aa-registration-services'
    | '/business-registration-licenses'
    | '/business-setup-services'
    | '/company-policies'
    | '/company-profile'
    | '/contact-us'
    | '/digital-business-services'
    | '/digital-signature-dsc-registration-services'
    | '/disclaimer'
    | '/esic-pf-registration-services'
    | '/fssai-food-license-registration-services'
    | '/gst-registration-return-filing-services'
    | '/huf-formation-registration-services'
    | '/import-export-code-iec-registration-services'
    | '/llp-compliance-packages'
    | '/msme-udyam-registration-services'
    | '/our-full-packages-services'
    | '/partnership-firm'
    | '/partnership-firm-registration-services'
    | '/privacy-policy'
    | '/private-limited-company'
    | '/professional-tax-registration-services'
    | '/shop-and-establishment-registration-services'
    | '/sole-proprietorship-registration-services'
    | '/startup-grant-loan-assistance-services'
    | '/startup-india-dpiit-registration-services'
    | '/startup-ngo-registration-services'
    | '/tax-holiday-section-80iac-services'
    | '/tax-registration-services'
    | '/terms-and-conditions'
    | '/accounting-audit-services/$slug'
    | '/bank-loan/$slug'
    | '/blog/$slug'
    | '/compliance/$slug'
    | '/consultation/$slug'
    | '/gst/$slug'
    | '/income-tax/$slug'
    | '/mca/$slug'
    | '/registrations/$slug'
    | '/tds-tcs/$slug'
    | '/accounting-audit-services'
    | '/bank-loan'
    | '/blog'
    | '/compliance'
    | '/consultation'
    | '/income-tax'
    | '/mca'
    | '/registrations'
    | '/tds-tcs'
  id:
    | '__root__'
    | '/'
    | '/accounting-audit-services'
    | '/bank-loan'
    | '/blog'
    | '/compliance'
    | '/consultation'
    | '/gst'
    | '/income-tax'
    | '/mca'
    | '/registrations'
    | '/tds-tcs'
    | '/80g-12aa-registration-services'
    | '/business-registration-licenses'
    | '/business-setup-services'
    | '/company-policies'
    | '/company-profile'
    | '/contact-us'
    | '/digital-business-services'
    | '/digital-signature-dsc-registration-services'
    | '/disclaimer'
    | '/esic-pf-registration-services'
    | '/fssai-food-license-registration-services'
    | '/gst-registration-return-filing-services'
    | '/huf-formation-registration-services'
    | '/import-export-code-iec-registration-services'
    | '/llp-compliance-packages'
    | '/msme-udyam-registration-services'
    | '/our-full-packages-services'
    | '/partnership-firm'
    | '/partnership-firm-registration-services'
    | '/privacy-policy'
    | '/private-limited-company'
    | '/professional-tax-registration-services'
    | '/shop-and-establishment-registration-services'
    | '/sole-proprietorship-registration-services'
    | '/startup-grant-loan-assistance-services'
    | '/startup-india-dpiit-registration-services'
    | '/startup-ngo-registration-services'
    | '/tax-holiday-section-80iac-services'
    | '/tax-registration-services'
    | '/terms-and-conditions'
    | '/accounting-audit-services/$slug'
    | '/bank-loan/$slug'
    | '/blog/$slug'
    | '/compliance/$slug'
    | '/consultation/$slug'
    | '/gst/$slug'
    | '/income-tax/$slug'
    | '/mca/$slug'
    | '/registrations/$slug'
    | '/tds-tcs/$slug'
    | '/accounting-audit-services/'
    | '/bank-loan/'
    | '/blog/'
    | '/compliance/'
    | '/consultation/'
    | '/income-tax/'
    | '/mca/'
    | '/registrations/'
    | '/tds-tcs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountingAuditServicesRouteRoute: typeof AccountingAuditServicesRouteRouteWithChildren
  BankLoanRouteRoute: typeof BankLoanRouteRouteWithChildren
  BlogRouteRoute: typeof BlogRouteRouteWithChildren
  ComplianceRouteRoute: typeof ComplianceRouteRouteWithChildren
  ConsultationRouteRoute: typeof ConsultationRouteRouteWithChildren
  GstRouteRoute: typeof GstRouteRouteWithChildren
  IncomeTaxRouteRoute: typeof IncomeTaxRouteRouteWithChildren
  McaRouteRoute: typeof McaRouteRouteWithChildren
  RegistrationsRouteRoute: typeof RegistrationsRouteRouteWithChildren
  TdsTcsRouteRoute: typeof TdsTcsRouteRouteWithChildren
  R80g12aaRegistrationServicesRoute: typeof R80g12aaRegistrationServicesRoute
  BusinessRegistrationLicensesRoute: typeof BusinessRegistrationLicensesRoute
  BusinessSetupServicesRoute: typeof BusinessSetupServicesRoute
  CompanyPoliciesRoute: typeof CompanyPoliciesRoute
  CompanyProfileRoute: typeof CompanyProfileRoute
  ContactUsRoute: typeof ContactUsRoute
  DigitalBusinessServicesRoute: typeof DigitalBusinessServicesRoute
  DigitalSignatureDscRegistrationServicesRoute: typeof DigitalSignatureDscRegistrationServicesRoute
  DisclaimerRoute: typeof DisclaimerRoute
  EsicPfRegistrationServicesRoute: typeof EsicPfRegistrationServicesRoute
  FssaiFoodLicenseRegistrationServicesRoute: typeof FssaiFoodLicenseRegistrationServicesRoute
  GstRegistrationReturnFilingServicesRoute: typeof GstRegistrationReturnFilingServicesRoute
  HufFormationRegistrationServicesRoute: typeof HufFormationRegistrationServicesRoute
  ImportExportCodeIecRegistrationServicesRoute: typeof ImportExportCodeIecRegistrationServicesRoute
  LlpCompliancePackagesRoute: typeof LlpCompliancePackagesRoute
  MsmeUdyamRegistrationServicesRoute: typeof MsmeUdyamRegistrationServicesRoute
  OurFullPackagesServicesRoute: typeof OurFullPackagesServicesRoute
  PartnershipFirmRoute: typeof PartnershipFirmRoute
  PartnershipFirmRegistrationServicesRoute: typeof PartnershipFirmRegistrationServicesRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  PrivateLimitedCompanyRoute: typeof PrivateLimitedCompanyRoute
  ProfessionalTaxRegistrationServicesRoute: typeof ProfessionalTaxRegistrationServicesRoute
  ShopAndEstablishmentRegistrationServicesRoute: typeof ShopAndEstablishmentRegistrationServicesRoute
  SoleProprietorshipRegistrationServicesRoute: typeof SoleProprietorshipRegistrationServicesRoute
  StartupGrantLoanAssistanceServicesRoute: typeof StartupGrantLoanAssistanceServicesRoute
  StartupIndiaDpiitRegistrationServicesRoute: typeof StartupIndiaDpiitRegistrationServicesRoute
  StartupNgoRegistrationServicesRoute: typeof StartupNgoRegistrationServicesRoute
  TaxHolidaySection80iacServicesRoute: typeof TaxHolidaySection80iacServicesRoute
  TaxRegistrationServicesRoute: typeof TaxRegistrationServicesRoute
  TermsAndConditionsRoute: typeof TermsAndConditionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms-and-conditions': {
      id: '/terms-and-conditions'
      path: '/terms-and-conditions'
      fullPath: '/terms-and-conditions'
      preLoaderRoute: typeof TermsAndConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tax-registration-services': {
      id: '/tax-registration-services'
      path: '/tax-registration-services'
      fullPath: '/tax-registration-services'
      preLoaderRoute: typeof TaxRegistrationServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tax-holiday-section-80iac-services': {
      id: '/tax-holiday-section-80iac-services'
      path: '/tax-holiday-section-80iac-services'
      fullPath: '/tax-holiday-section-80iac-services'
      preLoaderRoute: typeof TaxHolidaySection80iacServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/startup-ngo-registration-services': {
      id: '/startup-ngo-registration-services'
      path: '/startup-ngo-registration-services'
      fullPath: '/startup-ngo-registration-services'
      preLoaderRoute: typeof StartupNgoRegistrationServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/startup-india-dpiit-registration-services': {
      id: '/startup-india-dpiit-registration-services'
      path: '/startup-india-dpiit-registration-services'
      fullPath: '/startup-india-dpiit-registration-services'
      preLoaderRoute: typeof StartupIndiaDpiitRegistrationServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/startup-grant-loan-assistance-services': {
      id: '/startup-grant-loan-assistance-services'
      path: '/startup-grant-loan-assistance-services'
      fullPath: '/startup-grant-loan-assistance-services'
      preLoaderRoute: typeof StartupGrantLoanAssistanceServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sole-proprietorship-registration-services': {
      id: '/sole-proprietorship-registration-services'
      path: '/sole-proprietorship-registration-services'
      fullPath: '/sole-proprietorship-registration-services'
      preLoaderRoute: typeof SoleProprietorshipRegistrationServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop-and-establishment-registration-services': {
      id: '/shop-and-establishment-registration-services'
      path: '/shop-and-establishment-registration-services'
      fullPath: '/shop-and-establishment-registration-services'
      preLoaderRoute: typeof ShopAndEstablishmentRegistrationServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/professional-tax-registration-services': {
      id: '/professional-tax-registration-services'
      path: '/professional-tax-registration-services'
      fullPath: '/professional-tax-registration-services'
      preLoaderRoute: typeof ProfessionalTaxRegistrationServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/private-limited-company': {
      id: '/private-limited-company'
      path: '/private-limited-company'
      fullPath: '/private-limited-company'
      preLoaderRoute: typeof PrivateLimitedCompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partnership-firm-registration-services': {
      id: '/partnership-firm-registration-services'
      path: '/partnership-firm-registration-services'
      fullPath: '/partnership-firm-registration-services'
      preLoaderRoute: typeof PartnershipFirmRegistrationServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partnership-firm': {
      id: '/partnership-firm'
      path: '/partnership-firm'
      fullPath: '/partnership-firm'
      preLoaderRoute: typeof PartnershipFirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-full-packages-services': {
      id: '/our-full-packages-services'
      path: '/our-full-packages-services'
      fullPath: '/our-full-packages-services'
      preLoaderRoute: typeof OurFullPackagesServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/msme-udyam-registration-services': {
      id: '/msme-udyam-registration-services'
      path: '/msme-udyam-registration-services'
      fullPath: '/msme-udyam-registration-services'
      preLoaderRoute: typeof MsmeUdyamRegistrationServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llp-compliance-packages': {
      id: '/llp-compliance-packages'
      path: '/llp-compliance-packages'
      fullPath: '/llp-compliance-packages'
      preLoaderRoute: typeof LlpCompliancePackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import-export-code-iec-registration-services': {
      id: '/import-export-code-iec-registration-services'
      path: '/import-export-code-iec-registration-services'
      fullPath: '/import-export-code-iec-registration-services'
      preLoaderRoute: typeof ImportExportCodeIecRegistrationServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/huf-formation-registration-services': {
      id: '/huf-formation-registration-services'
      path: '/huf-formation-registration-services'
      fullPath: '/huf-formation-registration-services'
      preLoaderRoute: typeof HufFormationRegistrationServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gst-registration-return-filing-services': {
      id: '/gst-registration-return-filing-services'
      path: '/gst-registration-return-filing-services'
      fullPath: '/gst-registration-return-filing-services'
      preLoaderRoute: typeof GstRegistrationReturnFilingServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fssai-food-license-registration-services': {
      id: '/fssai-food-license-registration-services'
      path: '/fssai-food-license-registration-services'
      fullPath: '/fssai-food-license-registration-services'
      preLoaderRoute: typeof FssaiFoodLicenseRegistrationServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/esic-pf-registration-services': {
      id: '/esic-pf-registration-services'
      path: '/esic-pf-registration-services'
      fullPath: '/esic-pf-registration-services'
      preLoaderRoute: typeof EsicPfRegistrationServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/digital-signature-dsc-registration-services': {
      id: '/digital-signature-dsc-registration-services'
      path: '/digital-signature-dsc-registration-services'
      fullPath: '/digital-signature-dsc-registration-services'
      preLoaderRoute: typeof DigitalSignatureDscRegistrationServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/digital-business-services': {
      id: '/digital-business-services'
      path: '/digital-business-services'
      fullPath: '/digital-business-services'
      preLoaderRoute: typeof DigitalBusinessServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact-us': {
      id: '/contact-us'
      path: '/contact-us'
      fullPath: '/contact-us'
      preLoaderRoute: typeof ContactUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company-profile': {
      id: '/company-profile'
      path: '/company-profile'
      fullPath: '/company-profile'
      preLoaderRoute: typeof CompanyProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company-policies': {
      id: '/company-policies'
      path: '/company-policies'
      fullPath: '/company-policies'
      preLoaderRoute: typeof CompanyPoliciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business-setup-services': {
      id: '/business-setup-services'
      path: '/business-setup-services'
      fullPath: '/business-setup-services'
      preLoaderRoute: typeof BusinessSetupServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business-registration-licenses': {
      id: '/business-registration-licenses'
      path: '/business-registration-licenses'
      fullPath: '/business-registration-licenses'
      preLoaderRoute: typeof BusinessRegistrationLicensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/80g-12aa-registration-services': {
      id: '/80g-12aa-registration-services'
      path: '/80g-12aa-registration-services'
      fullPath: '/80g-12aa-registration-services'
      preLoaderRoute: typeof R80g12aaRegistrationServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tds-tcs': {
      id: '/tds-tcs'
      path: '/tds-tcs'
      fullPath: '/tds-tcs'
      preLoaderRoute: typeof TdsTcsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registrations': {
      id: '/registrations'
      path: '/registrations'
      fullPath: '/registrations'
      preLoaderRoute: typeof RegistrationsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mca': {
      id: '/mca'
      path: '/mca'
      fullPath: '/mca'
      preLoaderRoute: typeof McaRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/income-tax': {
      id: '/income-tax'
      path: '/income-tax'
      fullPath: '/income-tax'
      preLoaderRoute: typeof IncomeTaxRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gst': {
      id: '/gst'
      path: '/gst'
      fullPath: '/gst'
      preLoaderRoute: typeof GstRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultation': {
      id: '/consultation'
      path: '/consultation'
      fullPath: '/consultation'
      preLoaderRoute: typeof ConsultationRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance': {
      id: '/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof ComplianceRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bank-loan': {
      id: '/bank-loan'
      path: '/bank-loan'
      fullPath: '/bank-loan'
      preLoaderRoute: typeof BankLoanRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounting-audit-services': {
      id: '/accounting-audit-services'
      path: '/accounting-audit-services'
      fullPath: '/accounting-audit-services'
      preLoaderRoute: typeof AccountingAuditServicesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tds-tcs/': {
      id: '/tds-tcs/'
      path: '/'
      fullPath: '/tds-tcs/'
      preLoaderRoute: typeof TdsTcsIndexRouteImport
      parentRoute: typeof TdsTcsRouteRoute
    }
    '/registrations/': {
      id: '/registrations/'
      path: '/'
      fullPath: '/registrations/'
      preLoaderRoute: typeof RegistrationsIndexRouteImport
      parentRoute: typeof RegistrationsRouteRoute
    }
    '/mca/': {
      id: '/mca/'
      path: '/'
      fullPath: '/mca/'
      preLoaderRoute: typeof McaIndexRouteImport
      parentRoute: typeof McaRouteRoute
    }
    '/income-tax/': {
      id: '/income-tax/'
      path: '/'
      fullPath: '/income-tax/'
      preLoaderRoute: typeof IncomeTaxIndexRouteImport
      parentRoute: typeof IncomeTaxRouteRoute
    }
    '/consultation/': {
      id: '/consultation/'
      path: '/'
      fullPath: '/consultation/'
      preLoaderRoute: typeof ConsultationIndexRouteImport
      parentRoute: typeof ConsultationRouteRoute
    }
    '/compliance/': {
      id: '/compliance/'
      path: '/'
      fullPath: '/compliance/'
      preLoaderRoute: typeof ComplianceIndexRouteImport
      parentRoute: typeof ComplianceRouteRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRouteRoute
    }
    '/bank-loan/': {
      id: '/bank-loan/'
      path: '/'
      fullPath: '/bank-loan/'
      preLoaderRoute: typeof BankLoanIndexRouteImport
      parentRoute: typeof BankLoanRouteRoute
    }
    '/accounting-audit-services/': {
      id: '/accounting-audit-services/'
      path: '/'
      fullPath: '/accounting-audit-services/'
      preLoaderRoute: typeof AccountingAuditServicesIndexRouteImport
      parentRoute: typeof AccountingAuditServicesRouteRoute
    }
    '/tds-tcs/$slug': {
      id: '/tds-tcs/$slug'
      path: '/$slug'
      fullPath: '/tds-tcs/$slug'
      preLoaderRoute: typeof TdsTcsSlugRouteImport
      parentRoute: typeof TdsTcsRouteRoute
    }
    '/registrations/$slug': {
      id: '/registrations/$slug'
      path: '/$slug'
      fullPath: '/registrations/$slug'
      preLoaderRoute: typeof RegistrationsSlugRouteImport
      parentRoute: typeof RegistrationsRouteRoute
    }
    '/mca/$slug': {
      id: '/mca/$slug'
      path: '/$slug'
      fullPath: '/mca/$slug'
      preLoaderRoute: typeof McaSlugRouteImport
      parentRoute: typeof McaRouteRoute
    }
    '/income-tax/$slug': {
      id: '/income-tax/$slug'
      path: '/$slug'
      fullPath: '/income-tax/$slug'
      preLoaderRoute: typeof IncomeTaxSlugRouteImport
      parentRoute: typeof IncomeTaxRouteRoute
    }
    '/gst/$slug': {
      id: '/gst/$slug'
      path: '/$slug'
      fullPath: '/gst/$slug'
      preLoaderRoute: typeof GstSlugRouteImport
      parentRoute: typeof GstRouteRoute
    }
    '/consultation/$slug': {
      id: '/consultation/$slug'
      path: '/$slug'
      fullPath: '/consultation/$slug'
      preLoaderRoute: typeof ConsultationSlugRouteImport
      parentRoute: typeof ConsultationRouteRoute
    }
    '/compliance/$slug': {
      id: '/compliance/$slug'
      path: '/$slug'
      fullPath: '/compliance/$slug'
      preLoaderRoute: typeof ComplianceSlugRouteImport
      parentRoute: typeof ComplianceRouteRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRouteRoute
    }
    '/bank-loan/$slug': {
      id: '/bank-loan/$slug'
      path: '/$slug'
      fullPath: '/bank-loan/$slug'
      preLoaderRoute: typeof BankLoanSlugRouteImport
      parentRoute: typeof BankLoanRouteRoute
    }
    '/accounting-audit-services/$slug': {
      id: '/accounting-audit-services/$slug'
      path: '/$slug'
      fullPath: '/accounting-audit-services/$slug'
      preLoaderRoute: typeof AccountingAuditServicesSlugRouteImport
      parentRoute: typeof AccountingAuditServicesRouteRoute
    }
  }
}

interface AccountingAuditServicesRouteRouteChildren {
  AccountingAuditServicesSlugRoute: typeof AccountingAuditServicesSlugRoute
  AccountingAuditServicesIndexRoute: typeof AccountingAuditServicesIndexRoute
}

const AccountingAuditServicesRouteRouteChildren: AccountingAuditServicesRouteRouteChildren =
  {
    AccountingAuditServicesSlugRoute: AccountingAuditServicesSlugRoute,
    AccountingAuditServicesIndexRoute: AccountingAuditServicesIndexRoute,
  }

const AccountingAuditServicesRouteRouteWithChildren =
  AccountingAuditServicesRouteRoute._addFileChildren(
    AccountingAuditServicesRouteRouteChildren,
  )

interface BankLoanRouteRouteChildren {
  BankLoanSlugRoute: typeof BankLoanSlugRoute
  BankLoanIndexRoute: typeof BankLoanIndexRoute
}

const BankLoanRouteRouteChildren: BankLoanRouteRouteChildren = {
  BankLoanSlugRoute: BankLoanSlugRoute,
  BankLoanIndexRoute: BankLoanIndexRoute,
}

const BankLoanRouteRouteWithChildren = BankLoanRouteRoute._addFileChildren(
  BankLoanRouteRouteChildren,
)

interface BlogRouteRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteRouteChildren: BlogRouteRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteRouteWithChildren = BlogRouteRoute._addFileChildren(
  BlogRouteRouteChildren,
)

interface ComplianceRouteRouteChildren {
  ComplianceSlugRoute: typeof ComplianceSlugRoute
  ComplianceIndexRoute: typeof ComplianceIndexRoute
}

const ComplianceRouteRouteChildren: ComplianceRouteRouteChildren = {
  ComplianceSlugRoute: ComplianceSlugRoute,
  ComplianceIndexRoute: ComplianceIndexRoute,
}

const ComplianceRouteRouteWithChildren = ComplianceRouteRoute._addFileChildren(
  ComplianceRouteRouteChildren,
)

interface ConsultationRouteRouteChildren {
  ConsultationSlugRoute: typeof ConsultationSlugRoute
  ConsultationIndexRoute: typeof ConsultationIndexRoute
}

const ConsultationRouteRouteChildren: ConsultationRouteRouteChildren = {
  ConsultationSlugRoute: ConsultationSlugRoute,
  ConsultationIndexRoute: ConsultationIndexRoute,
}

const ConsultationRouteRouteWithChildren =
  ConsultationRouteRoute._addFileChildren(ConsultationRouteRouteChildren)

interface GstRouteRouteChildren {
  GstSlugRoute: typeof GstSlugRoute
}

const GstRouteRouteChildren: GstRouteRouteChildren = {
  GstSlugRoute: GstSlugRoute,
}

const GstRouteRouteWithChildren = GstRouteRoute._addFileChildren(
  GstRouteRouteChildren,
)

interface IncomeTaxRouteRouteChildren {
  IncomeTaxSlugRoute: typeof IncomeTaxSlugRoute
  IncomeTaxIndexRoute: typeof IncomeTaxIndexRoute
}

const IncomeTaxRouteRouteChildren: IncomeTaxRouteRouteChildren = {
  IncomeTaxSlugRoute: IncomeTaxSlugRoute,
  IncomeTaxIndexRoute: IncomeTaxIndexRoute,
}

const IncomeTaxRouteRouteWithChildren = IncomeTaxRouteRoute._addFileChildren(
  IncomeTaxRouteRouteChildren,
)

interface McaRouteRouteChildren {
  McaSlugRoute: typeof McaSlugRoute
  McaIndexRoute: typeof McaIndexRoute
}

const McaRouteRouteChildren: McaRouteRouteChildren = {
  McaSlugRoute: McaSlugRoute,
  McaIndexRoute: McaIndexRoute,
}

const McaRouteRouteWithChildren = McaRouteRoute._addFileChildren(
  McaRouteRouteChildren,
)

interface RegistrationsRouteRouteChildren {
  RegistrationsSlugRoute: typeof RegistrationsSlugRoute
  RegistrationsIndexRoute: typeof RegistrationsIndexRoute
}

const RegistrationsRouteRouteChildren: RegistrationsRouteRouteChildren = {
  RegistrationsSlugRoute: RegistrationsSlugRoute,
  RegistrationsIndexRoute: RegistrationsIndexRoute,
}

const RegistrationsRouteRouteWithChildren =
  RegistrationsRouteRoute._addFileChildren(RegistrationsRouteRouteChildren)

interface TdsTcsRouteRouteChildren {
  TdsTcsSlugRoute: typeof TdsTcsSlugRoute
  TdsTcsIndexRoute: typeof TdsTcsIndexRoute
}

const TdsTcsRouteRouteChildren: TdsTcsRouteRouteChildren = {
  TdsTcsSlugRoute: TdsTcsSlugRoute,
  TdsTcsIndexRoute: TdsTcsIndexRoute,
}

const TdsTcsRouteRouteWithChildren = TdsTcsRouteRoute._addFileChildren(
  TdsTcsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountingAuditServicesRouteRoute:
    AccountingAuditServicesRouteRouteWithChildren,
  BankLoanRouteRoute: BankLoanRouteRouteWithChildren,
  BlogRouteRoute: BlogRouteRouteWithChildren,
  ComplianceRouteRoute: ComplianceRouteRouteWithChildren,
  ConsultationRouteRoute: ConsultationRouteRouteWithChildren,
  GstRouteRoute: GstRouteRouteWithChildren,
  IncomeTaxRouteRoute: IncomeTaxRouteRouteWithChildren,
  McaRouteRoute: McaRouteRouteWithChildren,
  RegistrationsRouteRoute: RegistrationsRouteRouteWithChildren,
  TdsTcsRouteRoute: TdsTcsRouteRouteWithChildren,
  R80g12aaRegistrationServicesRoute: R80g12aaRegistrationServicesRoute,
  BusinessRegistrationLicensesRoute: BusinessRegistrationLicensesRoute,
  BusinessSetupServicesRoute: BusinessSetupServicesRoute,
  CompanyPoliciesRoute: CompanyPoliciesRoute,
  CompanyProfileRoute: CompanyProfileRoute,
  ContactUsRoute: ContactUsRoute,
  DigitalBusinessServicesRoute: DigitalBusinessServicesRoute,
  DigitalSignatureDscRegistrationServicesRoute:
    DigitalSignatureDscRegistrationServicesRoute,
  DisclaimerRoute: DisclaimerRoute,
  EsicPfRegistrationServicesRoute: EsicPfRegistrationServicesRoute,
  FssaiFoodLicenseRegistrationServicesRoute:
    FssaiFoodLicenseRegistrationServicesRoute,
  GstRegistrationReturnFilingServicesRoute:
    GstRegistrationReturnFilingServicesRoute,
  HufFormationRegistrationServicesRoute: HufFormationRegistrationServicesRoute,
  ImportExportCodeIecRegistrationServicesRoute:
    ImportExportCodeIecRegistrationServicesRoute,
  LlpCompliancePackagesRoute: LlpCompliancePackagesRoute,
  MsmeUdyamRegistrationServicesRoute: MsmeUdyamRegistrationServicesRoute,
  OurFullPackagesServicesRoute: OurFullPackagesServicesRoute,
  PartnershipFirmRoute: PartnershipFirmRoute,
  PartnershipFirmRegistrationServicesRoute:
    PartnershipFirmRegistrationServicesRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  PrivateLimitedCompanyRoute: PrivateLimitedCompanyRoute,
  ProfessionalTaxRegistrationServicesRoute:
    ProfessionalTaxRegistrationServicesRoute,
  ShopAndEstablishmentRegistrationServicesRoute:
    ShopAndEstablishmentRegistrationServicesRoute,
  SoleProprietorshipRegistrationServicesRoute:
    SoleProprietorshipRegistrationServicesRoute,
  StartupGrantLoanAssistanceServicesRoute:
    StartupGrantLoanAssistanceServicesRoute,
  StartupIndiaDpiitRegistrationServicesRoute:
    StartupIndiaDpiitRegistrationServicesRoute,
  StartupNgoRegistrationServicesRoute: StartupNgoRegistrationServicesRoute,
  TaxHolidaySection80iacServicesRoute: TaxHolidaySection80iacServicesRoute,
  TaxRegistrationServicesRoute: TaxRegistrationServicesRoute,
  TermsAndConditionsRoute: TermsAndConditionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
